//! Build-time embedding of the checked-in `webnovel/*.yaml` site definitions.
//!
//! The Worker has no filesystem at runtime, so the same user-editable YAML
//! files the native app loads are compiled into the binary as static strings.
//! `narou_rs::downloader::SiteSetting::load_bundled` parses and compiles them
//! (regexes + preprocess DSL) at composition time.
//!
//! Generation is deterministic: the emitted list is sorted by file name, so
//! rebuilds are stable and the order matches `load_all`'s sorted load order.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let webnovel_dir = manifest_dir
        .parent()
        .expect("worker_entry is a workspace member")
        .join("webnovel");

    let mut files: Vec<PathBuf> = fs::read_dir(&webnovel_dir)
        .unwrap_or_else(|error| {
            panic!(
                "cannot read bundled site definitions from {}: {error}",
                webnovel_dir.display()
            )
        })
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .and_then(|extension| extension.to_str())
                .is_some_and(|extension| extension == "yaml" || extension == "yml")
        })
        .collect();
    files.sort();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("bundled_sites.rs");

    let mut emitted = String::new();
    emitted.push_str("// @generated by worker_entry/build.rs — do not edit.\n");
    emitted.push_str("pub const BUNDLED_SITE_YAML: &[(&str, &str)] = &[\n");
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let content = fs::read_to_string(path).unwrap_or_else(|error| {
            panic!("cannot read bundled site definition {}: {error}", path.display())
        });
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .expect("site definition file name is UTF-8");
        emitted.push_str(&format!("    ({name:?}, {raw}),\n", raw = raw_string(&content)));
    }
    emitted.push_str("];\n");
    fs::write(&out_path, emitted).unwrap_or_else(|error| {
        panic!("cannot write generated site bundle {}: {error}", out_path.display())
    });
}

/// Emit `content` as a raw string literal, choosing a delimiter that cannot
/// appear inside the YAML text.
fn raw_string(content: &str) -> String {
    let hashes = (1..)
        .find(|count| !content.contains(&format!("\"{}", "#".repeat(*count))))
        .expect("raw string delimiter converges");
    let hashes = "#".repeat(hashes);
    format!("r{hashes}\"{content}\"{hashes}")
}
